ALTER TABLE sma_companies
    ADD COLUMN customer_group_id INT NULL,
    ADD COLUMN customer_group_name VARCHAR(255) NULL,
    ADD COLUMN name_ar VARCHAR(255) NULL,
    ADD COLUMN category VARCHAR(255) NULL,
    ADD COLUMN vat_no VARCHAR(255) NULL,
    ADD COLUMN cf1 VARCHAR(255) NULL,
    ADD COLUMN cf2 VARCHAR(255) NULL,
    ADD COLUMN cf3 VARCHAR(255) NULL,
    ADD COLUMN cf4 VARCHAR(255) NULL,
    ADD COLUMN cf5 VARCHAR(255) NULL,
    ADD COLUMN cf6 VARCHAR(255) NULL,
    ADD COLUMN invoice_footer TEXT NULL,
    ADD COLUMN payment_term INT NULL,
    ADD COLUMN logo VARCHAR(255) NULL,
    ADD COLUMN award_points INT NULL DEFAULT 0,
    ADD COLUMN deposit_amount DECIMAL(25, 4) NULL DEFAULT 0,
    ADD COLUMN price_group_id INT NULL,
    ADD COLUMN price_group_name VARCHAR(255) NULL,
    ADD COLUMN gst_no VARCHAR(255) NULL,
    ADD COLUMN ledger_account VARCHAR(255) NULL,
    ADD COLUMN parent_code VARCHAR(255) NULL,
    ADD COLUMN level INT NULL,
    ADD COLUMN fund_books_ledger VARCHAR(255) NULL,
    ADD COLUMN credit_card_ledger VARCHAR(255) NULL,
    ADD COLUMN cogs_ledger VARCHAR(255) NULL,
    ADD COLUMN inventory_ledger VARCHAR(255) NULL,
    ADD COLUMN sales_ledger VARCHAR(255) NULL,
    ADD COLUMN price_difference_ledger VARCHAR(255) NULL,
    ADD COLUMN discount_ledger VARCHAR(255) NULL,
    ADD COLUMN vat_on_sales_ledger VARCHAR(255) NULL,
    ADD COLUMN return_ledger VARCHAR(255) NULL,
    ADD COLUMN credit_limit DECIMAL(25, 4) NULL DEFAULT 0,
    ADD COLUMN balance DECIMAL(25, 4) NULL DEFAULT 0,
    ADD COLUMN gln VARCHAR(255) NULL,
    ADD COLUMN cr VARCHAR(255) NULL,
    ADD COLUMN external_id VARCHAR(255) NULL,
    ADD COLUMN cr_expiration DATE NULL,
    ADD COLUMN sfda_certificate VARCHAR(255) NULL,
    ADD COLUMN short_address VARCHAR(255) NULL,
    ADD COLUMN building_number VARCHAR(255) NULL,
    ADD COLUMN unit_number VARCHAR(255) NULL,
    ADD COLUMN additional_number VARCHAR(255) NULL,
    ADD COLUMN contact_name VARCHAR(255) NULL,
    ADD COLUMN contact_number VARCHAR(255) NULL,
    ADD COLUMN promessory_note_amount DECIMAL(25, 4) NULL DEFAULT 0,
    ADD COLUMN note VARCHAR(255) NULL,
    ADD COLUMN sales_agent VARCHAR(255) NULL,
    ADD COLUMN status VARCHAR(50) NULL,
    ADD COLUMN national_number VARCHAR(255) NULL;
