-- Legacy business tables for tenant databases.
-- Uses IF NOT EXISTS so existing production tenant schemas are not modified.

CREATE TABLE IF NOT EXISTS sma_purchase_orders
(
    id                    INT AUTO_INCREMENT PRIMARY KEY,
    reference_no          VARCHAR(50) UNIQUE,
    date                  DATETIME NULL,
    supplier_id           INT NULL,
    supplier              VARCHAR(255) NULL,
    warehouse_id          INT NULL,
    note                  TEXT NULL,
    total                 DECIMAL(12, 2) DEFAULT 0,
    old_total_net_purchase DECIMAL(12, 2) DEFAULT 0,
    total_net_purchase    DECIMAL(12, 2) DEFAULT 0,
    total_sale            DECIMAL(12, 2) DEFAULT 0,
    product_discount      DECIMAL(12, 2) DEFAULT 0,
    order_discount_id     INT NULL,
    order_discount        DECIMAL(12, 2) DEFAULT 0,
    total_discount        DECIMAL(12, 2) DEFAULT 0,
    product_tax           DECIMAL(12, 2) DEFAULT 0,
    order_tax_id          INT NULL,
    order_tax             DECIMAL(12, 2) DEFAULT 0,
    total_tax             DECIMAL(12, 2) DEFAULT 0,
    shipping              DECIMAL(12, 2) DEFAULT 0,
    grand_total           DECIMAL(12, 2) DEFAULT 0,
    paid                  DECIMAL(12, 2) DEFAULT 0,
    status                VARCHAR(50) DEFAULT 'draft',
    payment_status        VARCHAR(50) DEFAULT 'pending',
    shelf_status          VARCHAR(50) DEFAULT 'pending',
    created_by            INT NULL,
    updated_by            INT NULL,
    updated_at            DATETIME NULL,
    attachment            VARCHAR(255) NULL,
    payment_term          VARCHAR(50) NULL,
    due_date              DATE NULL,
    return_id             INT NULL,
    surcharge             DECIMAL(12, 2) DEFAULT 0,
    return_purchase_ref   VARCHAR(50) NULL,
    purchase_id           INT NULL,
    return_purchase_total DECIMAL(12, 2) DEFAULT 0,
    cgst                  DECIMAL(12, 2) DEFAULT 0,
    sgst                  DECIMAL(12, 2) DEFAULT 0,
    igst                  DECIMAL(12, 2) DEFAULT 0,
    tempstatus            VARCHAR(50) NULL,
    lotnumber             VARCHAR(50) NULL,
    validate              TINYINT(1) DEFAULT 0,
    purchase_invoice      VARCHAR(100) NULL,
    invoice_number        VARCHAR(100) NULL,
    sequence_code         VARCHAR(100) NULL,
    notification_id       INT NULL,
    is_transfer           TINYINT(1) DEFAULT 0,
    transfer_id           INT NULL,
    location_to           VARCHAR(100) NULL,
    transfer_by           INT NULL,
    transfer_at           DATETIME NULL,
    sending_notes         TEXT NULL,
    grn_id                INT NULL,
    grand_deal_discount   DECIMAL(12, 2) DEFAULT 0,
    active                TINYINT(1) DEFAULT 1,
    total_items_received  INT DEFAULT 0,
    grn_notes             TEXT NULL,
    received_by           INT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sma_purchase_order_items
(
    id                    INT AUTO_INCREMENT PRIMARY KEY,
    purchase_id           INT NULL,
    transfer_id           INT NULL,
    product_id            INT NULL,
    product_code          VARCHAR(100) NULL,
    product_name          VARCHAR(255) NULL,
    option_id             INT NULL,
    net_unit_cost         DECIMAL(12, 2) NULL,
    quantity              INT NULL,
    warehouse_id          INT NULL,
    item_tax              DECIMAL(12, 2) DEFAULT 0,
    tax_rate_id           INT NULL,
    tax                   DECIMAL(12, 2) DEFAULT 0,
    discount              DECIMAL(12, 2) DEFAULT 0,
    item_discount         DECIMAL(12, 2) DEFAULT 0,
    expiry                DATE NULL,
    subtotal              DECIMAL(12, 2) DEFAULT 0,
    quantity_balance      INT DEFAULT 0,
    date                  DATETIME NULL,
    status                VARCHAR(50) DEFAULT 'pending',
    unit_cost             DECIMAL(12, 2) DEFAULT 0,
    real_unit_cost        DECIMAL(12, 2) DEFAULT 0,
    sale_price            DECIMAL(12, 2) DEFAULT 0,
    quantity_received     INT DEFAULT 0,
    supplier_part_no      VARCHAR(100) NULL,
    purchase_item_id      INT NULL,
    product_unit_id       INT NULL,
    product_unit_code     VARCHAR(50) NULL,
    unit_quantity         DECIMAL(10, 2) DEFAULT 0,
    gst                   DECIMAL(12, 2) DEFAULT 0,
    cgst                  DECIMAL(12, 2) DEFAULT 0,
    sgst                  DECIMAL(12, 2) DEFAULT 0,
    igst                  DECIMAL(12, 2) DEFAULT 0,
    base_unit_cost        DECIMAL(12, 2) DEFAULT 0,
    subtotal2             DECIMAL(12, 2) DEFAULT 0,
    batchno               VARCHAR(50) NULL,
    serial_number         VARCHAR(100) NULL,
    bonus                 INT DEFAULT 0,
    discount1             DECIMAL(12, 2) DEFAULT 0,
    discount2             DECIMAL(12, 2) DEFAULT 0,
    totalbeforevat        DECIMAL(12, 2) DEFAULT 0,
    main_net              DECIMAL(12, 2) DEFAULT 0,
    warehouse_shelf       VARCHAR(100) NULL,
    avz_item_code         VARCHAR(50) NULL,
    second_discount_value DECIMAL(12, 2) DEFAULT 0,
    returned_quantity     INT DEFAULT 0,
    is_transfer           TINYINT(1) DEFAULT 0,
    discount3             DECIMAL(12, 2) DEFAULT 0,
    third_discount_value  DECIMAL(12, 2) DEFAULT 0,
    deal_discount         DECIMAL(12, 2) DEFAULT 0,
    deal_discount_value   DECIMAL(12, 2) DEFAULT 0,
    actual_quantity       INT DEFAULT 0,
    scanned_quantity      INT DEFAULT 0,
    new_scanned_quantity  INT DEFAULT 0,
    grn_comments          TEXT NULL,
    CONSTRAINT fk_purchase_order_items_purchase
        FOREIGN KEY (purchase_id) REFERENCES sma_purchase_orders (id) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sma_purchase_order_shelving
(
    id               INT AUTO_INCREMENT PRIMARY KEY,
    po_id            INT NULL,
    sale_id          INT NULL,
    zone_number      INT NULL,
    rack_number      VARCHAR(255) NULL,
    rack_unlock_time DATETIME NULL,
    rack_lock_time   DATETIME NULL,
    box_number       VARCHAR(255) NULL,
    box_unlock_time  DATETIME NULL,
    box_lock_time    DATETIME NULL,
    update_time      DATETIME NULL,
    status           VARCHAR(50) DEFAULT 'active',
    rack_number_old  VARCHAR(255) NULL,
    created_at       DATETIME NULL,
    updated_at       DATETIME NULL,
    CONSTRAINT fk_purchase_order_shelving_po
        FOREIGN KEY (po_id) REFERENCES sma_purchase_orders (id) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sma_purchase_order_shelving_items
(
    id                   INT AUTO_INCREMENT PRIMARY KEY,
    shelving_id          INT NULL,
    product_code         VARCHAR(255) NULL,
    batch_no             VARCHAR(255) NULL,
    expiry_date          DATE NULL,
    qty                  FLOAT NULL,
    status               VARCHAR(255) NULL,
    time_stamp           DATETIME NULL,
    cleaned_product_code VARCHAR(255) NULL,
    CONSTRAINT fk_purchase_order_shelving_items_shelving
        FOREIGN KEY (shelving_id) REFERENCES sma_purchase_order_shelving (id) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sma_sales
(
    id                        INT AUTO_INCREMENT PRIMARY KEY,
    date                      DATETIME NULL,
    reference_no              VARCHAR(255) NULL,
    customer_id               INT NULL,
    customer                  VARCHAR(255) NULL,
    biller_id                 INT NULL,
    biller                    VARCHAR(255) NULL,
    warehouse_id              INT NULL,
    note                      VARCHAR(255) NULL,
    staff_note                VARCHAR(255) NULL,
    total                     DECIMAL(6, 2) NULL,
    product_discount          DECIMAL(6, 2) NULL,
    order_discount_id         INT NULL,
    order_discount            DECIMAL(6, 2) NULL,
    total_discount            DECIMAL(6, 2) NULL,
    product_tax               DECIMAL(6, 2) NULL,
    order_tax_id              INT NULL,
    order_tax                 DECIMAL(6, 2) NULL,
    total_tax                 DECIMAL(6, 2) NULL,
    shipping                  DECIMAL(6, 2) NULL,
    grand_total               DECIMAL(6, 2) NULL,
    total_items               INT NULL,
    pos                       INT NULL,
    sale_status               VARCHAR(255) NULL,
    payment_status            VARCHAR(255) NULL,
    job_type                  VARCHAR(255) NULL,
    payment_term              INT NULL,
    due_date                  DATETIME NULL,
    paid                      DECIMAL(6, 2) NULL,
    created_by                INT NULL,
    updated_by                INT NULL,
    updated_at                DATETIME NULL,
    shop                      INT NULL,
    address_id                INT NULL,
    hash                      VARCHAR(255) NULL,
    payment_method            VARCHAR(255) NULL,
    delivery_type             VARCHAR(255) NULL,
    sequence_code             VARCHAR(255) NULL,
    coupon_code               VARCHAR(255) NULL,
    courier_id                INT NULL,
    courier_order_status      VARCHAR(255) NULL,
    courier_order_tracking_id VARCHAR(255) NULL,
    courier_label             VARCHAR(255) NULL,
    shipping_first_name       VARCHAR(255) NULL,
    shipping_last_name        VARCHAR(255) NULL,
    shipping_phone            VARCHAR(255) NULL,
    shipping_address1         VARCHAR(255) NULL,
    shipping_address2         VARCHAR(255) NULL,
    shipping_city             VARCHAR(255) NULL,
    shipping_zip              VARCHAR(255) NULL,
    shipping_province         VARCHAR(255) NULL,
    shipping_latitude         VARCHAR(255) NULL,
    shipping_longitude        VARCHAR(255) NULL,
    shipping_name             VARCHAR(255) NULL,
    shipping_country_code     VARCHAR(255) NULL,
    shipping_province_code    VARCHAR(255) NULL,
    shipping_country          VARCHAR(255) NULL,
    source_name               VARCHAR(255) NULL,
    shopify_tags              TEXT NULL
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sma_sale_items
(
    id                INT AUTO_INCREMENT PRIMARY KEY,
    sale_id           INT NULL,
    product_id        INT NULL,
    product_code      VARCHAR(255) NULL,
    product_name      VARCHAR(255) NULL,
    product_type      VARCHAR(255) NULL,
    net_cost          DECIMAL(6, 2) DEFAULT 0,
    net_unit_price    DECIMAL(6, 2) NULL,
    unit_price        DECIMAL(6, 2) NULL,
    quantity          DECIMAL(6, 2) NULL,
    warehouse_id      INT NULL,
    item_tax          DECIMAL(25, 4) NULL,
    tax_rate_id       INT NULL,
    tax               VARCHAR(55) NULL,
    discount          VARCHAR(55) NULL,
    item_discount     DECIMAL(25, 4) NULL,
    subtotal          DECIMAL(25, 4) NULL,
    real_unit_price   DECIMAL(25, 4) NULL,
    product_unit_id   INT NULL,
    product_unit_code VARCHAR(10) NULL,
    unit_quantity     DECIMAL(15, 4) NULL,
    serial_no         VARCHAR(255) NULL,
    expiry            DATE NULL,
    serial_number     VARCHAR(255) NULL,
    totalbeforevat    DECIMAL(24, 4) DEFAULT 0,
    main_net          DECIMAL(24, 4) DEFAULT 0,
    avz_item_code     VARCHAR(50) NULL,
    is_active         TINYINT(1) DEFAULT 1,
    is_reserved       TINYINT(1) DEFAULT 1,
    CONSTRAINT fk_sale_items_sale
        FOREIGN KEY (sale_id) REFERENCES sma_sales (id) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sma_warehouse_locations
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    zone    VARCHAR(50) NOT NULL,
    rack    VARCHAR(50) NOT NULL,
    section VARCHAR(50) NOT NULL,
    shelf   VARCHAR(50) NOT NULL,
    box     VARCHAR(50) NOT NULL,
    status  VARCHAR(50) DEFAULT 'enabled'
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_unicode_ci;
