ALTER TABLE sma_sales
    ADD COLUMN warning_note VARCHAR(255) NULL,
    ADD COLUMN total_net_sale DECIMAL(6, 2) NULL,
    ADD COLUMN additional_discount DECIMAL(6, 2) NULL,
    ADD COLUMN returns_total_deducted DECIMAL(6, 2) NULL,
    ADD COLUMN supplier_status VARCHAR(255) NULL,
    ADD COLUMN return_id INT NULL,
    ADD COLUMN surcharge DECIMAL(6, 2) NULL,
    ADD COLUMN attachment VARCHAR(255) NULL,
    ADD COLUMN return_sale_ref VARCHAR(255) NULL,
    ADD COLUMN sale_id INT NULL,
    ADD COLUMN return_sale_total DECIMAL(6, 2) NULL,
    ADD COLUMN rounding DECIMAL(6, 2) NULL,
    ADD COLUMN suspend_note VARCHAR(255) NULL,
    ADD COLUMN api TINYINT(1) NULL,
    ADD COLUMN reserve_id INT NULL,
    ADD COLUMN manual_payment DECIMAL(6, 2) NULL,
    ADD COLUMN cgst DECIMAL(6, 2) NULL,
    ADD COLUMN sgst DECIMAL(6, 2) NULL,
    ADD COLUMN igst DECIMAL(6, 2) NULL,
    ADD COLUMN sale_invoice VARCHAR(255) NULL,
    ADD COLUMN invoice_number VARCHAR(255) NULL,
    ADD COLUMN customer_name VARCHAR(255) NULL,
    ADD COLUMN mobile_number VARCHAR(255) NULL,
    ADD COLUMN instructions VARCHAR(255) NULL,
    ADD COLUMN cost_goods_sold DECIMAL(6, 2) NULL,
    ADD COLUMN courier_status VARCHAR(255) NULL,
    ADD COLUMN external_id VARCHAR(255) NULL,
    ADD COLUMN pickup_location_id INT NULL,
    ADD COLUMN courier_assignment_time DATETIME NULL,
    ADD COLUMN courier_pickup_time DATETIME NULL,
    ADD COLUMN courier_delivery_time DATETIME NULL,
    ADD COLUMN shipping_company VARCHAR(255) NULL,
    ADD COLUMN source VARCHAR(255) NULL;
